//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tours
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpelledStudents
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string LastName { get; set; }
        public string GroupID { get; set; }
        public System.DateTime DeductionDate { get; set; }
    }
}
