//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tours
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> GradeValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RUPID { get; set; }
        public Nullable<int> Term { get; set; }
    
        public virtual RUP RUP { get; set; }
        public virtual Student Student { get; set; }
    }
}
