//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tours
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAVGValue
    {
        public string GroupName { get; set; }
        public Nullable<int> AVGGRADE { get; set; }
    }
}
